import type { PatientTodayView } from "@pulso/shared";

/** Proyección PACIENTE de los datos de planes y agendas. Datos ficticios de demostración. */
export const MOCK_TODAY_VIEWS: Record<string, PatientTodayView> = {
  "demo-1": {
    patientId: "demo-1",
    date: "2026-06-10",
    plan: {
      id: "plan-demo-1",
      name: "Plan Hábitos Saludables",
      generalIndications:
        "Tomá agua durante el día. Priorizá alimentos frescos. " +
        "Registrá tus comidas en Mi Pulso para hacer el seguimiento.",
      meals: [
        {
          id: "meal-1",
          name: "Desayuno",
          moment: "breakfast",
          timeHint: "08:00",
          description: "Infusión, tostadas integrales, fruta de estación.",
          portionHint: "Porción orientativa.",
          order: 1,
        },
        {
          id: "meal-2",
          name: "Almuerzo",
          moment: "lunch",
          timeHint: "13:00",
          description:
            "Plato principal con proteína, vegetales y cereales integrales.",
          portionHint: "Porción orientativa.",
          order: 2,
        },
        {
          id: "meal-3",
          name: "Merienda",
          moment: "snack",
          timeHint: "17:00",
          description: "Fruta, yogur o colación liviana.",
          portionHint: "Porción orientativa.",
          order: 3,
        },
        {
          id: "meal-4",
          name: "Cena",
          moment: "dinner",
          timeHint: "20:30",
          description: "Cena liviana: sopa, ensalada o guiso suave.",
          portionHint: "Porción orientativa.",
          order: 4,
        },
      ],
    },
    agendaItems: [
      {
        id: "agenda-item-1",
        title: "Desayuno",
        type: "meal",
        moment: "breakfast",
        timeHint: "08:00",
        description: "Según tu plan: infusión, tostadas integrales, fruta.",
        order: 1,
      },
      {
        id: "agenda-item-2",
        title: "Hidratación mañana",
        type: "hydration",
        moment: "mid_morning",
        timeHint: "10:00",
        description: "Tomá al menos un vaso de agua.",
        order: 2,
      },
      {
        id: "agenda-item-3",
        title: "Almuerzo",
        type: "meal",
        moment: "lunch",
        timeHint: "13:00",
        description: "Según tu plan: proteína, vegetales y cereales.",
        order: 3,
      },
      {
        id: "agenda-item-4",
        title: "Merienda",
        type: "meal",
        moment: "snack",
        timeHint: "17:00",
        description: "Según tu plan: fruta, yogur o colación liviana.",
        order: 4,
      },
      {
        id: "agenda-item-5",
        title: "Registrar comidas en Mi Pulso",
        type: "reminder",
        moment: "afternoon",
        timeHint: "18:00",
        description: "Acordate de registrar tus comidas del día en Mi Pulso.",
        order: 5,
      },
      {
        id: "agenda-item-6",
        title: "Cena",
        type: "meal",
        moment: "dinner",
        timeHint: "20:30",
        description: "Según tu plan: cena liviana.",
        order: 6,
      },
    ],
    isDemoData: true,
  },

  "demo-2": {
    patientId: "demo-2",
    date: "2026-06-10",
    plan: {
      id: "plan-demo-2",
      name: "Plan Mantenimiento Activo",
      generalIndications:
        "Mantenés un buen equilibrio. Seguí registrando en Mi Pulso. " +
        "Hidratate bien durante el día.",
      meals: [
        {
          id: "meal-5",
          name: "Desayuno",
          moment: "breakfast",
          timeHint: "07:30",
          description: "Mate o café, tostadas con palta o queso untable.",
          portionHint: "Porción orientativa.",
          order: 1,
        },
        {
          id: "meal-6",
          name: "Colación de mañana",
          moment: "mid_morning",
          timeHint: "10:30",
          description: "Fruta o barritas de cereal.",
          portionHint: "Porción orientativa.",
          order: 2,
        },
        {
          id: "meal-7",
          name: "Almuerzo",
          moment: "lunch",
          timeHint: "12:30",
          description: "Proteína magra, ensalada variada, arroz integral.",
          portionHint: "Porción orientativa.",
          order: 3,
        },
        {
          id: "meal-8",
          name: "Merienda",
          moment: "snack",
          timeHint: "16:30",
          description: "Yogur natural o fruta.",
          portionHint: "Porción orientativa.",
          order: 4,
        },
        {
          id: "meal-9",
          name: "Cena",
          moment: "dinner",
          timeHint: "20:00",
          description: "Cena equilibrada, similar al almuerzo pero más ligera.",
          portionHint: "Porción orientativa.",
          order: 5,
        },
      ],
    },
    agendaItems: [
      {
        id: "agenda-item-7",
        title: "Desayuno",
        type: "meal",
        moment: "breakfast",
        timeHint: "07:30",
        description: "Según tu plan: mate o café, tostadas.",
        order: 1,
      },
      {
        id: "agenda-item-8",
        title: "Colación de mañana",
        type: "meal",
        moment: "mid_morning",
        timeHint: "10:30",
        description: "Según tu plan: fruta o barrita.",
        order: 2,
      },
      {
        id: "agenda-item-9",
        title: "Almuerzo",
        type: "meal",
        moment: "lunch",
        timeHint: "12:30",
        description: "Según tu plan: proteína magra, ensalada, arroz.",
        order: 3,
      },
      {
        id: "agenda-item-10",
        title: "Merienda",
        type: "meal",
        moment: "snack",
        timeHint: "16:30",
        description: "Según tu plan: yogur o fruta.",
        order: 4,
      },
      {
        id: "agenda-item-11",
        title: "Cena",
        type: "meal",
        moment: "dinner",
        timeHint: "20:00",
        description: "Según tu plan: cena equilibrada.",
        order: 5,
      },
    ],
    isDemoData: true,
  },

  "demo-3": {
    patientId: "demo-3",
    date: "2026-06-10",
    plan: null,
    agendaItems: [],
    isDemoData: true,
  },
};

export const DEMO_PATIENT_LABELS: Record<string, string> = {
  "demo-1": "Valentina Morales",
  "demo-2": "Marcos Rodríguez",
  "demo-3": "Carolina Benzaquen",
};
